apiVersion: v1
kind: Service
metadata:
  name: tgram-bot
  labels:
    app: tgram-bot
spec:
  selector:
    app: tgram-bot
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090